# Generated by Django 4.2.19 on 2025-02-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
