# Generated by Django 4.2.19 on 2025-02-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_medium',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verbosity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
